---
aws_access: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

ec2_region: us-east-1
ec2_zone: us-east-1a
ec2_image: ami-9c78c0f5 # ami-ef795786 - Ubuntu 13.04 raring # ami-9c78c0f5 - Ubuntu 12.04 precise
ec2_instance_type: m1.large
ec2_keypair: swb-keypair


