---
- name: Gather facts from all hosts
  hosts: "{{ environ|default('dev') }}_all_"
  remote_user: ubuntu 

- name: render the test template
  hosts: localhost
  tasks:

  - template: src=test-strings.j2 dest=/tmp/test-seeds

  - debug: msg="look at /tmp/test-seeds for the output"
