# ansible-playbook -i plugins/ec2.py eval.yml 
---

# COMMON: Ensure we have our base machine setup correctly
- name: Setup Common Facilities
  hosts: tag_group_evaluation
  remote_user: ubuntu
  sudo: true
  accelerate: false
  roles:
    - { role: common, tags: common }

# DATABASE: Ensure our database tier is running correctly
- name: Configure databases
  hosts: tag_group_evaluation
  remote_user: ubuntu
  sudo: true
  accelerate: true
  accelerate_port: 5099
  vars_files:
    - vars/eval.yml
    - vars/credentials.yml
  roles:
    - { role: dse, tags: [ cassandra, dse ] }
    - { role: datomic, tags: datomic }
  tags: databases

# SWITCHBOARD: Deploy/Upgrade Switchboard and Orchestra
- name: Configure Switchboard/Orchestra 
  hosts: tag_group_evaluation
  remote_user: deploy
  accelerate: true
  accelerate_port: 5098
  vars_files:
    - vars/eval.yml
    - vars/credentials.yml
  roles:
    - role: immutant
      immutant_address: "{{ switchboard_address }}"
      immutant_port: "{{ switchboard_port }}"
      tags: immutant
    - role: immutant-app
      app_name: "switchboard"
      app_root: "/switchboard"
      app_git_repo: "ssh://git@github.com/vitalreactor/switchboard"
      app_git_version: "{{ switchboard_version }}"
      app_profiles: "{{ switchboard_profiles }}"
      app_vhost: "{{ switchboard_vhost }}"
      app_bind: "{{ switchboard_address }}"
      app_context: "{{ switchboard_context }}"
      app_config: "{{ switchboard_config }}"
      tags: switchboard
    - role: clojure-app
      app_user: "deploy"
      app_name: "orchestra"
      app_dir: "/var/lib/swb-orchestra"
      app_root: "/orchestra"
      app_git_repo: "ssh://git@github.com/vitalreactor/switchboard"
      app_git_version: "{{ orchestra_commit }}"
      app_profile: "{{ orchestra_profiles }}"
      app_args: ""
      app_log_dir: "/var/log/clojure"
      switchboard_client_url: "{{ switchboard_client_url }}"
      switchboard_port: "80"
      switchboard_app: "1"
      tags: orchestra
  tags: application
      
# PROXY: Ensure we have a local proxy ready to route requests
- name: Virtual server proxies
  hosts: tag_group_evaluation
  remote_user: deploy
  accelerate: true
  accelerate_port: 5098
  vars_files:
    - vars/eval.yml
  roles:
    - role: eval-proxy
      app_dir: "/var/lib/swb-orchestra"
      app_root: "/orchestra"
      switchboard_vhost: "{{ switchboard_vhost }}"
      switchboard_proxy_port: "8080"
      tags: eval-proxy
  tags: proxy


