# ansible-playbook -i plugins/ec2.py eval.yml 
---

# COMMON: Ensure we have our base machine setup correctly
- name: Setup Common Facilities
  hosts: tag_group_evaluation
  remote_user: ubuntu
  sudo: true
  accelerate: false
  roles:
    - { role: common, tags: common }

# DATABASE: Ensure our database tier is running correctly
- name: Configure databases
  hosts: tag_group_evaluation
  remote_user: ubuntu
  sudo: true
  accelerate: true
  accelerate_port: 5099
  vars_files:
    - vars/eval.yml
    - vars/credentials.yml
  roles:
    - { role: dse, tags: [ cassandra, dse ] }
    - { role: datomic, tags: datomic }
  tags: databases

# SWITCHBOARD: Deploy/Upgrade Switchboard and Orchestra
- name: Configure Switchboard (pulls in Immutant role)
  hosts: tag_group_evaluation
  remote_user: deploy
  accelerate: true
  accelerate_port: 5098
  vars_files:
    - vars/eval.yml
    - vars/credentials.yml
  roles:
    - { role: datomic-client, maven_user: immutant, tags: datomic-client }
    - role: immutant-app
      app_name: "switchboard"
      app_root: "/switchboard"
      app_git_version: "{{ switchboard_version }}"
      app_profiles: "{{ switchboard_profiles }}"
      app_vhost: "{{ switchboard_vhost }}"
      app_context: "{{ switchboard_context }}"
      app_config: "{{ switchboard_config }}"
#    - { role: clojure-app, commit: "{{ orchestra_commit }}", tags: orchestra }
  tags: switchboard
  
# LOAD BALANCER / PROXY: Ensure we have a local proxy ready to route requests
#- name: Virtual server proxies
#  remote_user: deploy
#  roles:
#    - { role: proxy, tags: proxy }


