---
- name: Check datomic installation
  command: "ls /home/{{ maven_user }}/.m2/repository/com/datomic/datomic-pro/{{ datomic_version }}"
  register: datomic_exists
  ignore_errors: true

- name: Create temp directory
  file: state=directory path=/tmp/datomic owner={{ maven_user }}
  sudo: true
  when: datomic_exists|failed

- name: Download datomic
  s3: bucket=vr-dist object=/archives/{{ datomic_filename }}.zip dest=/tmp/datomic/{{ datomic_filename }}.zip mode=get aws_access_key={{ aws_access }} aws_secret_key={{ aws_secret }}
  sudo: true
  when: datomic_exists|failed

- name: Unpack datomic
  command: chdir=/tmp/datomic unzip {{ datomic_filename }}.zip
  sudo: true
  when: datomic_exists|failed

- name: Local install to the maven_user repository
  command: su "{{ maven_user }}" -c 'bin/maven-install' chdir="/tmp/datomic/{{ datomic_filename }}"
  register: datomic_install
  sudo: true
  when: datomic_exists|failed

- name: Remove temp directory
  file: path=/tmp/datomic
        state=absent
        recurse=yes
  sudo: true
  when: datomic_install|success