---
galaxy_info:
  author: Matt Martz
  description: Install and configure the New Relic System Monitor Daemon
  license: Apache License, Version 2.0
  min_ansible_version: 1.4
  platforms:
    - name: EL
      versions:
        - 5
        - 6
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - lenny
        - squeeze
        - wheezy
  categories:
    - monitoring
dependencies: []
