# Deploy github-based apps to immutant via source
---

# Connect to github
- name: test for hostkey file
  shell: cat ~/.ssh/known_hosts
  register: known_hosts
  ignore_errors: true

- name: remove the old host key, if any
  command: "ssh-keygen -R github.com"
  when: known_hosts|success

- name: make sure we have the current hostkey
  shell: "ssh-keyscan github.com >> ~/.ssh/known_hosts"

- name: ensure up to date application source
  git: repo={{ app_git_repo }}
       dest=/var/lib/immutant/applications/{{ app_name }}
       version={{ app_git_version }}
       depth=1
       update=yes
  register: git_pull

- name: make immutant the owner of the tree
  file: path=/var/lib/immutant/applications/{{ app_name }}
        recurse=yes
        owner=immutant
  sudo: true

- name: deploy the application configuration file
  copy: src={{ app_config }}
        dest=/var/lib/immutant/applications/{{ app_name }}{{ app_root }}/config/config.edn
        owner=immutant
  sudo: true
  tags: switchboard-deploy
  
# Deploy to immutant
- name: Deploy the application to the local immutant
  environment:
    IMMUTANT_HOME: /var/lib/immutant/current
  command: "su immutant -c 'lein with-profile {{ app_profiles }} immutant deploy --context-path {{ app_context }}' chdir=/var/lib/immutant/applications/{{ app_name }}{{ app_root }}" # --virtual-host {{ app_bind }}
  sudo: true
  tags: switchboard-deploy
  notify:
    - restart immutant # Until Clojure 1.6 is available