---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False

- name: Configure New Relic Sysmond
  template:
    src: nrsysmond.cfg.j2
    dest: /etc/newrelic/nrsysmond.cfg
    group: newrelic
    owner: root
    mode: 0640
  notify:
    - Restart New Relic
  when: newrelic_loaded_os_family|default(False) != False

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes
