---
- name: install old boto
  apt: name=python-boto state=present

- name: add the deploy public key
  authorized_key: user=ubuntu key="{{ item }}"
  with_file:
    - id_rsa_newdeploy-key.pub

# Install deployer private key into deploying account
- name: install our deployer key
  s3: aws_access_key={{ ec2_access_key }}
      aws_secret_key={{ ec2_secret_key }}
      mode=get
      bucket={{ github_s3_bucket_name }}
      object=/id_rsa_newdeploy-key
      dest=/home/ubuntu/.ssh/id_rsa

- name: set secure permissions on private key
  file: path=/home/ubuntu/.ssh/id_rsa
        owner=ubuntu group=ubuntu
        mode=0600

- name: make sure we have the current hostkey
  shell: "ssh-keyscan github.com >> ~/.ssh/known_hosts"
