---
- name: Deploy the initial common configuration and setup for DSE hosts
  hosts: localhost
  sudo: yes

  pre_tasks:

  tasks:
   - name: Gather EC2-based facts
     ec2_facts:

  roles:
  - common
  - java
  - db-dse

# TODO: deal with the seeds configuration file
