---
- name: Create Instance
  ec2: > 
   id="{{ id }}"
   region="{{ ec2_region }}"
   zone="{{ ec2_zone }}"
   keypair="{{ ec2_keypair }}"
   instance_type="{{ ec2_instance_type }}"
   image="{{ ec2_image }}"
   group="{{ group }}"
   user_data="{{ type }}"
   instance_tags="{'Name':'Evaluation', 'type':'{{ type }}', 'id':'{{ id }}', 'group':'{{ group }}'}"
   count="{{ ncount }}"
   wait=true
  register: ec2

- name: Add new instance to host group 
  add_host: name="{{ item.public_dns_name }}" groupname="{{ register_group }}"
  with_items: ec2.instances

