---
#Provision some instances:
- name: launch non-vpc instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars/main.yml
  

  tasks:

  - name: Include the variables specific to the vpc
    include_vars: envs/adhoc

  - name: Launch instances
    ec2: 
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ item.keypair }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ item.image }}"
      instance_tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      count_tag: "{{ item.count_tag }}"
      wait: true
    register: ec2
    with_items: ec2_instances

  # - name: get instance IDs to tag the cassandra instances
  #   shell: >
  #     aws ec2 describe-instances --filters "Name=tag-value,Values=dev_db" | grep InstanceId | awk '{print $2}' | sed s/\"//g | sed s/\,//g | grep -v "\[" | sort -u | head -1
  #   register: cassandra_seed
  #   environment: aws_creds

  # - name: tag the cassandras clusters for later use
  #   shell: >
  #     aws ec2 create-tags --resource {{ cassandra_seed }} --tags Key=cassandra_seed,Value= 
  #   environment: aws_creds

  # - name: the seed is also the datomic master
  #   shell: >
  #     aws ec2 create-tags --resource {{ cassandra_seed }} --tags Key=datomic_master,Value=