---
# Perform a rolling update of the Cassandra from 1.2 to 2.0
#
- name: Upgrade Cassandra hosts
  hosts: tag_Name_{{environ|default('dev')}}_db:tag_Name_{{environ|default('dev')}}_db_seed
  remote_user: ubuntu
  sudo: true
  serial: 1

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"


  pre_tasks:

  - name: repair the cassandra host
    command: nodetool repair

  - name: drain the cassandra host
    command: nodetool snapshot

  - name: drain the cassandra host
    command: nodetool drain

  - name: stop cassandra
    service: name=dse state=stopped

  # re-apply roles and any config changes
  roles:
  - db-dse

  post_tasks:
  - name: restart cassandra
    service: name=dse state=restarted

  - name: upgradesstables
    command: nodetool upgradesstables


  - name: wait until cassandra comes back up
    wait_for: host={{ inventory_hostname }} port={{ cassandra_intermode_port }}

  - name: wait 60 seconds for the cluster negotiation to settle
    pause: minutes=1
