## You must place a yml config in your .ssh location for this playbook task to run!

- name: Gather facts from all hosts
  hosts: "{{ environ|default('dev') }}_all_"
  remote_user: ubuntu 

- name: Deploy Initial Configs Switchboard Orchestra Common
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  sudo: true

  roles:
  - common
  - java
  - app-github

- include: deploy-app-clojure-config-source.yml
  when: switchboard_deployfrom_source == True
- include: deploy-app-clojure-config-archive.yml
  when: switchboard_deployfrom_source == False
- include: deploy-app-deploy.yml
