## You must place a yml config in your .ssh location for this playbook task to run!

- name: Gather facts from all hosts
  hosts: "{{ environ|default('dev') }}_all_"
  remote_user: ubuntu 

- name: Deploy Initial Configs Switchboard Orchestra Common
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  sudo: true

  vars_prompt:

    - name: "orchestra_git_version"
      prompt: "Orchestra release version"
      default: HEAD
      private: no

  roles:
  - common
  - java
  - app-clojure-config