- name: bring instances up to date
  hosts: dev_all
  remote_user: ubuntu
  sudo: true
  tasks:
  - name: required packages
    apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
      - python-apt
  
  - name: dist upgrade
    apt: upgrade=dist
    with_items: ec2.instances
  
  - name: reboot to make sure everything is fresh
    shell: /sbin/reboot &
    with_items: ec2.instances

  - name: wait for the server to go down (reboot)
    local_action: wait_for host={{ item.public_ip }} port=22 state=stopped
    with_items: ec2.instances

  - name: Wait for the server to wake back up
    local_action: wait_for host={{ item.public_ip }} port=22 delay=30
    with_items: ec2.instances