---
# Perform a snaphot backup of all of the cassandra nodes for later saving to s3
# 
#
- name: Upgrade Cassandra hosts
  hosts: tag_Name_{{environ|default('dev')}}_db:tag_Name_{{environ|default('dev')}}_db_seed
  remote_user: ubuntu
  sudo: true
  serial: 1

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"


  pre_tasks:
  - name: snapshot the cassandra host
    command: nodetool snapshot



 
