---
# Perform a rolling update of the Immutant Server config and Swictchoboard code and configuration, one host at a time.
#
# Notes:
#
# This is the general pattern for a rolling upgrade. 
# 
# The "serial: 1" setting controls how many nodes are restarted at a time. For large clusters,
# increase this.
#
# Right now we are relying on nginx failover btu should move toward removing from load balancer before? TODO
#
- name: Upgrade All application hosts
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  sudo: true
  serial: 1

  vars_prompt:

    - name: "switchboard_git_version"
      prompt: "Switchboard release version"
      default: HEAD
      private: no

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"

  pre_tasks:
  # nothing right now..need to take out of load balancer or does iummutant handle?

  # re-apply roles and any config changes
  roles:
  - app-immutant-config
  - app-deploy

  post_tasks:
  # none righ tnow, assume immutant is started back up

- include: deploy-proxy-nginx-config.yml