---

# Restart Immutant
#
- name: Upgrade All application hosts
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  sudo: true
  serial: 1

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"

  pre_tasks:
  # nothing right now..need to take out of load balancer or does iummutant handle?

  # re-apply roles and any config changes
  tasks:

  - name: restart immutant
    service: name=immutant state=restarted
    sudo: true

  - name: wait until immutant comes back up, simple smoke test and to enforce rolling restart
    wait_for: host={{ inventory_hostname }} port={{ switchboard_port }}

  post_tasks:
  # noen righ tnow, assume immutant is started back up



